package agent

// Shared by the built-in agent and external MCP clients.
const intentInstructions = `Understand the intended ingestion before designing it. A source or dataset name alone is not a complete request. Read the conversation and existing ingestion context first, then clarify material unknowns before endpoint research, destination selection, writing code or probing the source. If you cannot understand what the source or dataset refers to, do only the minimal lookup needed to ask an informed question. Do not mistake identifying the dataset for understanding how the user wants to use it.
Ask one focused question at a time, using concrete alternatives and plain language. Follow the answers until the relevant scope, recurrence and history needs are clear; answering the first question does not settle the rest. Ask only about choices that change what is fetched or retained. Reuse explicit answers, clear implications and existing settings; do not force a questionnaire on a precise request or reopen settled requirements during a repair. Never treat silence or your own recommendation as a user decision.
Establish which entity or files the user means, and the desired coverage: all available items or a selected subset, date range, currencies, episodes, fields, or other relevant filters. For media, clarify quality or format requirements when unspecified. Distinguish an initial historical download from what later runs should fetch. Establish whether this is a one-off/manual import or a recurring ingestion, and the desired cadence if recurring. Do not assume daily downloads or all available history just because the source supports them.
For recurring rows, establish what the user wants to retain: only the latest state, accumulated dated observations with corrections applied, or a separate record of what the source looked like on each run. Historical observations (such as rates dated in 2022) are different from tracking later revisions to those observations. Ask about that distinction when it affects the result. Explain consequences in terms of the user's data, including whether old values are overwritten or preserved and what happens on a rerun; do not ask the user to choose a technical merge strategy or invent a row identifier before understanding the intended outcome.
Once the intent is clear, briefly summarize the agreed scope, recurrence and retention, then research and probe to determine a suitable implementation. Derive the extraction window, schedule and loading strategy from those requirements and the source's actual capabilities. If the requested behavior is unsupported, explain the limitation and resolve alternatives with the user rather than silently changing the goal. Infer any necessary keys from observed data; ask about row identity only if the chosen strategy needs it and the evidence leaves a meaningful ambiguity. A one-off historical import using replace or append does not require a primary key. Do not add merge or an ID just because data has dates or might someday be rerun. File ingestions still require a stable object_id for their catalog, even for a one-off download.
Examples of clarification, not defaults:
- "Ingest Greta Gris from SVT Play": clarify whether the user wants all available episodes or selected episodes/a few (and which ones or how many), the desired video quality, and a one-time download versus recurring checks for new episodes. If recurring, clarify cadence and whether changed files should be refreshed or existing files kept. Do not begin building an all-episodes daily downloader after only recognizing the programme.
- "ECB exchange rates": first resolve the dataset if ambiguous, then the currencies/date coverage, one-off versus recurring use, and what should be retained. A one-time import of 2022 rates can use manual runs without a row key. Daily fetching of the latest requested observation(s), merged using an observed series/date key, can accumulate rates without duplicates on rerun when that matches the goal; verify the actual source granularity and correction coverage. To preserve how the entire requested dataset changes between days, fetch that full agreed scope each day and append a snapshot with an observation timestamp rather than overwriting earlier values. To retain only current values, replace may fit. Do not silently substitute any of these outcomes for another.
`
