package agent

// Shared by the built-in agent and external MCP clients.
const objectInstructions = `
File ingestion uses an objects destination. These file-specific rules replace the row extraction/loading rules above when ingesting documents, images, audio or video. One source collection = one YAML = one dedicated schema with one objects table and its files. A single file is a collection of one. Use context to select an objects destination; its Path is a directory containing objects.duckdb and files/. If none exists, ask the user to add one in /destinations.
For write_script, set table="objects", schema to a unique descriptive lower_snake_case ingestion name, and collection to the source collection name (defaults to schema). fetch(secret, limit) yields dictionaries with required string fields object_id, source_uri, filename. object_id must be stable across changed content, filenames and expiring download URLs. filename is a safe relative path, preserving bucket subdirectories. Optional fields: source_version (string validator/version, never an assumed checksum), source_modified_at (ISO timestamp with timezone), content_type, metadata (JSON object), download_url (ephemeral URL, excluded from catalog and probe output). source_uri must be a stable credential-free reference; put signed URLs in download_url. Put source-specific fields such as title, report year, channel, dimensions or duration in metadata. Never fabricate metadata.
For plain HTTP downloads Pompos streams download_url or source_uri automatically. For authenticated requests, buckets, or video downloaders, define download(object, target_path, secret) to write exactly one complete file to target_path. It is called only during validation or loading, never the discovery probe. Use managed source secrets and declared Python dependencies. This hook may write inside the supplied staging directory; it must not write to final destinations, the catalog, or unrelated paths. Use timeouts and raise on incomplete downloads. For buckets, use the SDK to list with pagination and download the selected object. For YouTube, use yt-dlp's Python API, one video per object, write the exact target_path, disable playlists and auxiliary outputs. External executables such as FFmpeg must already be installed; do not install them from source scripts. Select a format compatible with the environment and user's requirements.
Choose strategy="update" to download new or changed files. A matching nonempty source_version skips an intact stored file; absent a validator, update downloads again to check the content. strategy="skip" retains existing intact files regardless of source changes. primary_key must be empty; the catalog uses object_id. Both policies retain files missing from subsequent source listings. Explain these policies instead of row replace/append/merge.
test_script discovers up to five objects without downloading file contents. File validation defaults to three objects, maximum ten, downloads in a temporary directory and DuckDB catalog, and repeats the same sample to check identity and counts. Downloads across both passes default to a 50 MiB budget and 90-second execution timeout. For larger files, set max_bytes (up to 10737418240, 10 GiB) and timeout_seconds (up to 1800, 30 minutes) on propose_validation or validate_ingestion; account for both passes when no source version is available. Select a budget appropriate to the user-authorized file size and show it in the validation proposal. Never silently change the requested video quality or validate different code than will be saved. Successful validation includes a metadata preview. Validation does not prove all source permissions, full pagination or production destination access. The objects table catalogs only successfully published files, one row per object with its latest stored version. Queryable metadata includes object_id, source_uri, uri, filename, content_type, size_bytes, sha256, source_version, source_modified_at, first_seen_at, last_seen_at, downloaded_at and metadata JSON. The normal save, scheduling and run workflow applies.
`
